### ISSUE TITLE
'template' config option

### ISSUE THREAD

**Issue by johnshepherd** [sleeping-owl/admin-lte-template#2]
Hi,

Have been trying to install this, followed this procedure:
1. Added dependency to composer
2. Added service provider
3. Published assets

Next, I looked to add the line into `config/admin.php` for the template - but I couldn't see an existing array key for this? I tried adding it anyway, but it didn't seem to make a difference. Am I missing something here? I can switch out the `bladePrefix` to `admin-lte::` but this causes errors that I'm guessing that the `view()` method in Template.php solves.

Thanks for your help!

**Comment by sleeping-owl** [comment]
This is template for the upcoming sleeping-owl/admin 3.0 version (in development branch now http://sleeping-owl.github.io/v3/en/Getting_Started/Installation.html).

For the current version you can try to use https://github.com/gionnivaleriana/laravel-adminlte

**Comment by johnshepherd** [comment]
Ah understood, thank you.
