### ISSUE TITLE
Publish assets command not working

### ISSUE THREAD

**Issue by xnhinzkyx** [sleeping-owl/admin-lte-template#8]
Hello,

I use admin V3 using Laravel 5.1 and after I run the command:
php artisan vendor:publish --provider=SleepingOwl/Admin/AdminLteTemplateServiceProvider --tag=assets-lte

It gives me this message:
Nothing to publish for tag [assets-lte].

I follow the process step by step.

In app/config.php I add this line for provider:
SleepingOwl\AdminLteTemplate\AdminLteTemplateServiceProvider::class,

Is there something I miss?

Thanks.

**Comment by Jagy2014** [comment]
I have the same issue, how to fix that?

**Comment by oldskool73** [comment]
try just `php artisan vendor:publish --tag=assets-lte` ... worked for me.

**Comment by xnhinzkyx** [comment]
Yeah that works.. Thanks!!

**Comment by calidalux** [comment]
Thanks!
